feat(web): favorites support local fiction
FishHawk/auto-novel pull request #89
Opened 2024-06-20 00:32 UTC by 153264

浏览器 indexdb volumes
新增 favorite 表 表字段 id: string, title: string
修改 metadata 表 新增 favoriteId: string

页面优化
我的收藏：本地小说 /favorite/local/default
支持管理标签，批量对文章分类

~~Sakura工作区 /workspace/sakura~~
~~本地小说 支持管理标签，批量对文章分类~~

https://github.com/FishHawk/auto-novel/issues/87

此issuse提到工作区需要全面升级，此pr暂时不调整工作区页面
https://github.com/FishHawk/auto-novel/issues/88#issuecomment-2171932427

2024-06-20 17:15 UTC, FishHawk commented
这两天有点事，明天晚上我看看

2024-06-21 17:29 UTC, FishHawk requested changes

2024-06-21 17:29 UTC, FishHawk commented on web/src/pages/bookshelf/components/BookshelfLocalControl.vue
用Promise.all有潜在的隐患，而且Indexeddb似乎不支持并发写操作，因此速度可能区别不大。等下我改成普通循环，以后有需要再优化吧。

2024-06-21 17:29 UTC, FishHawk commented on web/src/data/local/LocalVolumeDao.ts
收藏夹本身是有限的，没必要塞进indexeddb里面，等下我会移动到localstorage里面。

2024-06-21 17:29 UTC, FishHawk commented on web/src/pages/bookshelf/components/BookshelfLocalList.vue
这里我打算直接在indexeddb版本号升级里面批量编辑，就不用留下负债了。

2024-06-21 17:31 UTC, FishHawk approved these changes

2024-06-21 17:57 UTC, FishHawk commented on web/src/data/local/LocalVolumeDao.ts
稍微牵扯的有点太多了，想一步到位缓存web/wenku收藏夹的话，得在数据层区分下dataSource和repository，明天接着做。

2024-06-21 21:18 UTC, 153264 commented on web/src/pages/bookshelf/components/BookshelfLocalList.vue
> +    volumes.value.filter((v) => v.favoriteId == props.favoredId),
这里这样实现可能会导致没有 favoriteId 的数据显示不出来
要不然之前的小说查不到了
把 默认收藏夹 当成 全部收藏夹 了

2024-06-21 21:27 UTC, 153264 commented on web/src/pages/bookshelf/components/BookshelfLocalList.vue
https://github.com/FishHawk/auto-novel/blob/1f160ff32af7c64bbfb968573a2d39ce255fd621/web/src/data/local/LocalVolumeDao.ts#L42

那对应创建`metadata`的时候也要加一个默认的`favoriteId`

2024-06-22 13:20 UTC, FishHawk commented
搞定了，顺便把本地缓存收藏夹也一起做了，有空测试下吗？
没时间的话我过会直接merge了。

2024-06-22 13:51 UTC, merged

2024-06-22 15:12 UTC, FishHawk commented
啊，想起来了。
因为最终tag表得存到服务器那边，要是懒得返工的话，我先加接口？
另外tag id我想了想，会让过滤/搜索变得有点难搞，而且如果还用uuid的话，会让tag数组增大很多倍，有点头疼。

2024-06-22 23:49 UTC, 153264 commented
> 另外tag id我想了想，会让过滤/搜索变得有点难搞，而且如果还用uuid的话，会让tag数组增大很多倍，有点头疼。

我建议是直接多对多的关系，加一张中间表
这样方便搜索

2024-06-23 08:35 UTC, FishHawk commented
> 我建议是直接多对多的关系，加一张中间表

你意思的tag表和tag-小说关系表？不会方便的。现在搜索两个方案，一是把tag数组塞进es里面，二是使用mongodb自带的全文搜索，不管哪个都比中间表方便，但都需要标签字面量。